git:
  pagers:
    - colorArg: always
      pager: delta --paging=never
gui:
  nerdFontsVersion: "3"
  theme:
    activeBorderColor:
      - "bold"
    cherryPickedCommitBgColor:
      - "#fb4934"
    cherryPickedCommitFgColor:
      - "#83a598"
    defaultFgColor:
      - "#fbf1c7"
    inactiveBorderColor:
      - "#928374"
    optionsTextColor:
      - "#83a598"
    searchingActiveBorderColor:
      - "bold"
    selectedLineBgColor:
      - "#504945"
    unstagedChangesColor:
      - "#fb4934"
os:
  editPreset: nvim
