#!/usr/bin/env sh

sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# mission-control desktop labels
yabai -m space 1 --label code
yabai -m space 2 --label web
yabai -m space 3 --label flex
yabai -m space 4 --label flex2
yabai -m space 5 --label notes
yabai -m space 6 --label mail
yabai -m space 7 --label calendar
yabai -m space 8 --label social
yabai -m space 9 --label media

# window rules
yabai -m rule --add app="^(Notion|Notes)$" space=notes
yabai -m rule --add app="^(GoogleCalendar|Calendar)$" space=calendar
yabai -m rule --add app="^(Discord|Messages)$" space=social
yabai -m rule --add app="^Spotify$" space=media
yabai -m rule --add app="^(Calculator|Archive Utility|System Settings|Raycast|Flow|Digital Color Meter)$" manage=off

# global settings
yabai -m config                                 \
    mouse_follows_focus          off            \
    focus_follows_mouse          off            \
    window_origin_display        default        \
    window_placement             second_child   \
    window_zoom_persist          on             \
    window_topmost               off            \
    window_shadow                on             \
    window_animation_duration    0.0            \
    window_animation_frame_rate  120            \
    window_opacity_duration      0.0            \
    active_window_opacity        1              \
    normal_window_opacity        1              \
    window_opacity               on             \
    insert_feedback_color        0xffd75f5f     \
    split_ratio                  0.50           \
    split_type                   auto           \
    auto_balance                 off            \
    top_padding                  7              \
    bottom_padding               7              \
    left_padding                 7              \
    right_padding                7              \
    window_gap                   7              \
    layout                       bsp            \
    mouse_modifier               fn             \
    mouse_action1                move           \
    mouse_action2                resize         \
    mouse_drop_action            swap           \

echo "yabai configuration loaded.."
