return {
  "ThePrimeagen/harpoon",
  config = true,
  keys = {
    {
      "<Leader>a",
      function()
        require("harpoon.mark").add_file()
      end,
    },
    {
      "<C-e>",
      function()
        require("harpoon.ui").toggle_quick_menu()
      end,
    },
    {
      "<S-h>",
      function()
        require("harpoon.ui").nav_file(1)
      end,
    },
    {
      "<S-k>",
      function()
        require("harpoon.ui").nav_file(2)
      end,
    },
    {
      "<S-m>",
      function()
        require("harpoon.ui").nav_file(3)
      end,
    },
    {
      "<S-l>",
      function()
        require("harpoon.ui").nav_file(4)
      end,
    },
  },
}
